dist: jammy
group: edge
arch: ppc64le

before_script:
  - sudo usermod -aG lxd $USER
  
script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - lxd init --minimal
  - lxc --debug ls 

  # - lxc launch ubuntu:22.04 test
  # - lxc ls
  # - lxc exec test -- apt update -y
  # - lxc exec test -- apt install alien -y
  # - lxc exec test -- alien

  - sudo ls -lha /var/snap/lxd/common/lxd/logs/
  - sudo cat /var/snap/lxd/common/lxd/logs/lxd.log
