dist: jammy
group: edge
arch: ppc64le

# before_script:
#   - sudo usermod -aG lxd $USER
#   - newgrp lxd

before_script:
  - sudo chmod +x test.sh
  
script:
  - id
  - cat /proc/self/uid_map
  - cat /proc/self/gid_map
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - sudo lxd init --minimal
  # - sudo sudo -E -u travis -g lxd -i 'lxd init --minimal'

  # - travis_wait 20 sudo lxc --debug launch ubuntu:22.04 test -c security.privileged=true
  # - sudo lxc ls

  - sudo ./test.sh
  - sudo lxc exec test -- apt update -y
  - sudo lxc exec test -- apt install alien -y
  - sudo lxc exec test -- alien -V

after_script:
  - sudo ls -lha /var/snap/lxd/common/lxd/logs/
  - sudo cat /var/snap/lxd/common/lxd/logs/lxd.log
  - sudo cat /var/snap/lxd/common/lxd/logs/test
