dist: jammy
group: edge
arch: ppc64le

script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - sudo snap restart lxd
  - lxd --debug
  - lxd init --minimal
  # - lxc ls

  # - lxc launch ubuntu:22.04 test
  # - lxc ls
  # - lxc exec test -- apt update -y
  # - lxc exec test -- apt install alien -y
  # - lxc exec test -- alien
  - ls -lha /var/log/lxd
  - wc /var/log/lxd/lxd.log
  - cat /var/log/lxd/lxd.log
