dist: jammy
group: edge
arch: ppc64le

# before_script:
#   - sudo usermod -aG lxd $USER
#   - newgrp lxd
  
script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - sudo lxd init --minimal
  # - sudo sudo -E -u travis -g lxd -i 'lxd init --minimal'

  - travis_wait sudo lxc --debug launch ubuntu:22.04 test
  - sudo lxc ls
  - sudo lxc exec test -- apt update -y
  - sudo lxc exec test -- apt install alien -y
  - sudo lxc exec test -- alien

after_script:
  - sudo ls -lha /var/snap/lxd/common/lxd/logs/
  - sudo cat /var/snap/lxd/common/lxd/logs/lxd.log
