dist: jammy
group: edge
arch: ppc64le

script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - sudo snap restart lxd
  - lxd --debug
  - lxd init --minimal
  - lxc ls

  # - lxc launch ubuntu:22.04 test
  # - lxc ls
  # - lxc exec test -- apt update -y
  # - lxc exec test -- apt install alien -y
  # - lxc exec test -- alien

  - sudo ls -lha /var/snap/lxd/common/lxd/logs/
  - sudo cat /var/snap/lxd/common/lxd/logs/lxd.log
