dist: jammy
group: edge
arch: ppc64le

script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  - sudo snap restart lxd
  # - lxd --debug
  # - lxd init --minimal
  # - lxc ls

  # - lxc launch ubuntu:22.04 test
  - lxc ls
  # - lxc exec test -- apt update -y
  # - lxc exec test -- apt install alien -y
  # - lxc exec test -- alien
  - sudo ls /var/log
  - sudo ls -lha /var/log/lxd
  - sudo wc /var/log/lxd/lxd.log
  - sudo cat /var/log/lxd/lxd.log
  - journalctl -u snap.lxd.service 
