dist: focal
arch: ppc64le

script:
  - snap list
  - sudo snap refresh lxd --channel=latest/stable
  # - lxd init --minimal
  - lxc ls

  - lxc launch ubuntu:22.04 test
  - lxc ls
  - lxc exec test -- apt update -y
  - lxc exec test -- apt install alien -y
  - lxc exec test -- alien
